"""init

Revision ID: fcea58223ca4
Revises: 
Create Date: 2026-02-19 14:59:33.601785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcea58223ca4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('diplome', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('offres_emploi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('competences', sa.String(length=200), nullable=True),
    sa.Column('salaire', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_candidature', sa.DateTime(), nullable=False),
    sa.Column('candidat_id', sa.Integer(), nullable=False),
    sa.Column('offre_emploi_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidat_id'], ['candidats.id'], ),
    sa.ForeignKeyConstraint(['offre_emploi_id'], ['offres_emploi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidatures')
    op.drop_table('offres_emploi')
    op.drop_table('candidats')
    # ### end Alembic commands ###
